// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef ARM_H
#define ARM_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "CANTalon.h"
#include "AnalogInput.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Arm: public Subsystem
{
private:
	std::shared_ptr<CANTalon> adjust;
	std::shared_ptr<AnalogInput> rotationDetect;

	const float MIN_VOLTS = 1.1f; //all the way in
	const float MAX_VOLTS = 4.0f; //all the way out

	/*
	 * This means that 2.55 is half way
	 * 1.825 is 1/4 way
	 * 3.275 is 3/4 way
	 */


public:
	Arm();
	float GetArm();
	float GetDegrees();
	//float SetArm(float x);
	float Get();
	void Set(float x);
	void InitDefaultCommand();
	float getMin();
	float getMax();
	void setArmPosition(float pos);
	float getArmPosition();
	void SetMode(CANTalon::ControlMode mode);
};

#endif
