// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Drivetrain.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/DriveJoystick.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Drivetrain::Drivetrain() :
		Subsystem("Drivetrain")
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	cANTalon1 = RobotMap::drivetrainCANTalon1;
	cANTalon2 = RobotMap::drivetrainCANTalon2;
	cANTalon3 = RobotMap::drivetrainCANTalon3;
	cANTalon4 = RobotMap::drivetrainCANTalon4;
	robotDrive = RobotMap::drivetrainRobotDrive;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Drivetrain::InitDefaultCommand()
{
	// Set the default command for a subsystem here.
	/*SetTankDrive, SetArcadeDrive, and SetManualDrive are all methods that will be put in the Drivetrain subststem file. [HERE] 
They will be called from commands. Commands are called in a few different ways. 
They can be called automatically by a button press, they can be called by a command group, 
or they can be called manually by calling the Command's Start() method. More info on how this works can be found here: 
http://wpilib.screenstepslive.com/s/4485/m/13810/l/241904-running-commands-on-joystick-input*/
	// SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

	SetDefaultCommand(new DriveJoystick());
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

void Drivetrain::SetTankDrive(float leftPower, float rightPower) {
	robotDrive->TankDrive(leftPower, rightPower, true);
	//should the bool value (SquaredInputs) be true? don't know what it does
}

void Drivetrain::SetArcadeDrive(float movePower, float rotatePower) {
	robotDrive->ArcadeDrive(movePower, rotatePower, true);
	//also don't know what squaredInputs (bool) does
}
