// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/Autonomous.h"
#include "Commands/DriveJoystick.h"
#include "Commands/InvertControls.h"
#include "Commands/ServoPush.h"
#include "Commands/ServoClamp.h"
#include "Commands/FireShooter.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI()
{
	// Process operator interface input here.
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	//joystick buttons
	//GUNNER
	gunner.reset(new Joystick(1));

	fireButton.reset(new JoystickButton(gunner.get(), 1));
	fireButton->WhenPressed(new FireShooter());

	servoPush.reset(new JoystickButton(gunner.get(), 5));
	servoPush->WhileHeld(new ServoPush());

	servoClamp.reset(new JoystickButton(gunner.get(), 6));
	servoClamp->WhileHeld(new ServoClamp());
	//DRIVER
	driver.reset(new Joystick(0));

	//resetButton.reset(new JoystickButton(driver.get(), 2));
	//resetButton->WhenPressed(new DriveJoystick());

	lowGear.reset(new JoystickButton(driver.get(), 5));
	//lowGear->WhenPressed(new lowGear()); TODO fix when new shifter stuff is added

	highGear.reset(new JoystickButton(driver.get(), 6));




	// SmartDashboard Buttons

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getDriver()
{
	return driver;
}

std::shared_ptr<Joystick> OI::getGunner()
{
	return gunner;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

