// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/Autonomous.h"
#include "Commands/BreachChevalDeFrise.h"
#include "Commands/BreachDrawbridge.h"
#include "Commands/BreachLowBar.h"
#include "Commands/BreachMoat.h"
#include "Commands/BreachPortcullis.h"
#include "Commands/BreachRamparts.h"
#include "Commands/BreachRockWall.h"
#include "Commands/BreachRoughTerrain.h"
#include "Commands/BreachSallyPort.h"
#include "Commands/DriveJoystick.h"
#include "Commands/DriveSet.h"
#include "Commands/DriveToDefense.h"
#include "Commands/FireShooter.h"
#include "Commands/PrepareShooter.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI()
{
	// Process operator interface input here.
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	gunner.reset(new Joystick(1));

	fireButton.reset(new JoystickButton(gunner.get(), 1));
	fireButton->WhenPressed(new FireShooter());
	driver.reset(new Joystick(0));

	resetButton.reset(new JoystickButton(driver.get(), 2));
	resetButton->WhenPressed(new DriveJoystick());

	// SmartDashboard Buttons
	SmartDashboard::PutData("PrepareShooter", new PrepareShooter());
	SmartDashboard::PutData("FireShooter", new FireShooter());
	SmartDashboard::PutData("DriveToDefense", new DriveToDefense());
	SmartDashboard::PutData("Autonomous", new Autonomous());
	SmartDashboard::PutData("BreachLowBar", new BreachLowBar());
	SmartDashboard::PutData("BreachRoughTerrain", new BreachRoughTerrain());
	SmartDashboard::PutData("BreachRockWall", new BreachRockWall());
	SmartDashboard::PutData("BreachSallyPort", new BreachSallyPort());
	SmartDashboard::PutData("BreachDrawbridge", new BreachDrawbridge());
	SmartDashboard::PutData("BreachRamparts", new BreachRamparts());
	SmartDashboard::PutData("BreachMoat", new BreachMoat());
	SmartDashboard::PutData("BreachChevalDeFrise", new BreachChevalDeFrise());
	SmartDashboard::PutData("BreachPortcullis", new BreachPortcullis());
	SmartDashboard::PutData("DriveSet", new DriveSet());
	SmartDashboard::PutData("DriveJoystick", new DriveJoystick());
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getDriver()
{
	return driver;
}

std::shared_ptr<Joystick> OI::getGunner()
{
	return gunner;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
