// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include <Commands/Shooter/ShooterControl.h>
#include "Robot.h"

#include "Commands/Arm/ArmToPosition.h"
#include "Commands/Drive/DriveJoystick.h"
#include "Commands/Arm/ArmMove.h"
#include "Commands/Drive/DriveSet.h"
#include "Commands/Autonomous/Autonomous.h"
#include "Commands/Drive/DriveDistance.h"
#include <SmartDashboard/SmartDashboard.h>


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
std::shared_ptr<Drivetrain> Robot::drivetrain;
std::shared_ptr<ShooterWheels> Robot::shooterwheels;
std::shared_ptr<ShooterRotation> Robot::shooterrotation;
std::shared_ptr<ShooterLever> Robot::shooterlever;
std::shared_ptr<Arm> Robot::arm;
std::shared_ptr<Shifter> Robot::shifter;
std::unique_ptr<OI> Robot::oi;


void Robot::RobotInit()
{
	RobotMap::init();
	navx = new NavX(SPI::Port::kMXP);

	drivetrain.reset(new Drivetrain());
	shooterwheels.reset(new ShooterWheels());
	shooterrotation.reset(new ShooterRotation());
	arm.reset(new Arm());
	shooterlever.reset(new ShooterLever());
	shifter.reset(new Shifter());

	oi.reset(new OI());

	//SmartDashboard::PutData("FireShooter", new FireShooter());
	//SmartDashboard::PutData("Autonomous", new Autonomous());
	SmartDashboard::PutData("DriveSet", new DriveSet(0.0f, 0.0f));
	SmartDashboard::PutData("DriveJoystick", new DriveJoystick());
	SmartDashboard::PutData("DriveDistance", new DriveDistance(12));


	chooser.reset(new SendableChooser());
	chooser->AddDefault("Low Bar", new Autonomous(Defense::LOW_BAR));
	chooser->AddObject("Cheval de Frise", new Autonomous(Defense::CHEVAL_DE_FRISE));
	chooser->AddObject("Draw Bridge", new Autonomous(Defense::DRAW_BRIDGE));
	chooser->AddObject("Moat", new Autonomous(Defense::MOAT));
	chooser->AddObject("Portcullis", new Autonomous(Defense::PORTCULLIS));
	chooser->AddObject("Rock Wall", new Autonomous(Defense::ROCK_WALL));
	chooser->AddObject("Rough Terrain", new Autonomous(Defense::ROUGH_TERRAIN));
	chooser->AddObject("Sally Port", new Autonomous(Defense::SALLY_PORT));

	SmartDashboard::PutData("Autonomous Defense Chooser", chooser.get());

	// instantiate the command used for the autonomous period
	//autonomousCommand.reset((Command *) chooser->GetSelected());
	drivejoystick.reset(new DriveJoystick());
	//armmove.reset(new ArmMove());
	//autowheels.reset(new AutoWheels());

	RobotMap::drivetrainEncoder.get()->Reset();
	RobotMap::drivetrainEncoder2.get()->Reset();
}

void Robot::DisabledInit()
{

}

void Robot::DisabledPeriodic()
{
	Scheduler::GetInstance()->Run();
}

void Robot::AutonomousInit()
{
	autonomousCommand.reset((Command *) chooser->GetSelected());

	if (autonomousCommand.get() != nullptr)
		autonomousCommand->Start();

	shooterrotation->SetAngle(3);
}

void Robot::AutonomousPeriodic()
{
	Scheduler::GetInstance()->Run();
}

void Robot::TeleopInit()
{if (autonomousCommand.get() != nullptr)
		autonomousCommand->Cancel();

	drivejoystick->Start();
	//armmove->Start();
	//autowheels->Start();
	shifter->Set(Shifter::LOW);
}

void Robot::TeleopPeriodic()
{
	Scheduler::GetInstance()->Run();

	SmartDashboard::PutNumber("Shooter Absolute Encoder", RobotMap::shooterEncoder.get()->GetVoltage());
	SmartDashboard::PutNumber("Arm Absolute Encoder", RobotMap::armRotationDetect.get()->GetVoltage());

	//Encoder
	SmartDashboard::PutNumber("Left encoder ticks", RobotMap::drivetrainEncoder->Get());
	SmartDashboard::PutNumber("Left encoder 'distance'", RobotMap::drivetrainEncoder->GetDistance());
	SmartDashboard::PutNumber("Right encoder ticks", RobotMap::drivetrainEncoder2->Get());
	SmartDashboard::PutNumber("Right encoder 'distance'", RobotMap::drivetrainEncoder2->GetDistance());

	shooterrotation->SetSpeed(oi->getGunner()->GetRawAxis(5));

	//shooterrotation->SetSpeed(oi->getGunner()->GetRawAxis(3));
}

void Robot::TestPeriodic()
{
	lw->Run();
}

START_ROBOT_CLASS(Robot);
