// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<Talon> RobotMap::drivetrainTalon1;
std::shared_ptr<Talon> RobotMap::drivetrainTalon2;
std::shared_ptr<Talon> RobotMap::drivetrainTalon3;
std::shared_ptr<Talon> RobotMap::drivetrainTalon4;
std::shared_ptr<RobotDrive> RobotMap::drivetrainRobotDrive;
std::shared_ptr<Servo> RobotMap::shooterLeverServo1;
std::shared_ptr<CANTalon> RobotMap::armAdjust;
std::shared_ptr<AnalogInput> RobotMap::armRotationDetect;
std::shared_ptr<CANTalon> RobotMap::shooterRotateMotor;
std::shared_ptr<AnalogInput> RobotMap::shooterLeverDetect;
std::shared_ptr<Servo> RobotMap::shifterServo1;
std::shared_ptr<Servo> RobotMap::shifterServo2;
std::shared_ptr<CANTalon> RobotMap::leftFlywheel;
std::shared_ptr<CANTalon> RobotMap::rightFlywheel;
std::shared_ptr<Encoder> RobotMap::drivetrainEncoder;
std::shared_ptr<Encoder> RobotMap::drivetrainEncoder2;
std::shared_ptr<AnalogInput> RobotMap::shooterEncoder;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init()
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow *lw = LiveWindow::GetInstance();

	/* Servo values: 0
	 * Talon values: 1,2,3,4
	 *
	 *
	 * Talon and Servo both use PWM. Make sure their values are different!
	 */

	//PWM
	shooterLeverServo1.reset(new Servo(6));
	lw->AddActuator("ShooterLever", "Lever Servo", shooterLeverServo1);

	shifterServo2.reset(new Servo(2));
			lw->AddActuator("Shifter", "Right Shifter Servo", shifterServo2);

	shifterServo1.reset(new Servo(3));
		lw->AddActuator("Shifter", "Left Shifter Servo", shifterServo1);

	drivetrainTalon1.reset(new Talon(4)); //front left
	lw->AddActuator("Drivetrain", "Front Left (1)", drivetrainTalon1);

	drivetrainTalon2.reset(new Talon(5)); //rear left
	lw->AddActuator("Drivetrain", "Rear Left (2)", drivetrainTalon2);

	drivetrainTalon3.reset(new Talon(0)); //front right
	lw->AddActuator("Drivetrain", "Front Right (3)", drivetrainTalon3);

	drivetrainTalon4.reset(new Talon(1)); //rear right
	lw->AddActuator("Drivetrain", "Rear Right (4)", drivetrainTalon4);

	drivetrainRobotDrive.reset(
			new RobotDrive(drivetrainTalon1, drivetrainTalon2,
					drivetrainTalon3, drivetrainTalon4)); //fl, rl, fr, rr

	//CAN
	armAdjust.reset(new CANTalon(2));
	lw->AddActuator("Arm", "Arm Motor", armAdjust);

	shooterRotateMotor.reset(new CANTalon(1));
	lw->AddActuator("ShooterRotate", "Shooter Rotate Motor", shooterRotateMotor);

	leftFlywheel.reset(new CANTalon(3));
	lw->AddActuator("ShooterWheels", "Flywheel Motor (1)", leftFlywheel);

    rightFlywheel.reset(new CANTalon(4));
	lw->AddActuator("ShooterWheels", "Flywheel Motor (2)", rightFlywheel);

	 //Analog I/O
	shooterLeverDetect.reset(new AnalogInput(1));
	lw->AddActuator("ShooterLever", "Ball Detector IR", shooterLeverDetect);

	armRotationDetect.reset(new AnalogInput(3));
	lw->AddActuator("Arm", "Magnetic Encoder", armRotationDetect);

	drivetrainRobotDrive->SetSafetyEnabled(true);

	shooterEncoder.reset(new AnalogInput(2));
	lw->AddActuator("ShooterRotation", "Shooter Rotation Encoder", shooterEncoder);

	drivetrainRobotDrive->SetSafetyEnabled(false);
	drivetrainRobotDrive->SetExpiration(0.1);
	drivetrainRobotDrive->SetSensitivity(0.5);
	drivetrainRobotDrive->SetMaxOutput(1.0);

	//Digital I/O
	drivetrainEncoder.reset(new Encoder(0, 1));
	lw->AddActuator("drivetrain", "QuadEncoder", drivetrainEncoder);

	drivetrainEncoder2.reset(new Encoder(2, 3));
	lw->AddActuator("drivetrain", "QuadEncoder 2", drivetrainEncoder2);

	/*
	 * Hall effects 4 and 5
	 * Shooter encoder talon 1
	 *
	 *
	 */

	//4, 5 Hall effects
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
