// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Autonomous.h"
#include "AutoBreach.h"
#include "../Arm/ArmToPosition.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Autonomous::Autonomous()
{
	AddSequential(new ArmToPosition(0));
	AddSequential(new AutoBreach(Robot::Defense::LOW_BAR)); //change this before every match
	AddSequential(new DriveSet(0.5f, 0.5f));
	//TODO AddSequential(new AutoAlign(FindTarget::RIGHT));
	/*
	 * When we have the Jetson machine learning running, we'll have a command that reads values from the Jetson to the roboRIO.
	 * This might be called AddSequential(new ReadJetson);
	 * Then, that command will set the value of a Robot::Defense variable.
	 * Finally, we'll do AddSequential(new BreachAuto(Some Robot::Defense value)); which will automatically do what's needed to breach the command.
	 */
}
